version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=plataforma_cursos
      - JWT_SECRET=your_super_secret_jwt_key_here_change_in_production
    depends_on:
      - mysql
    volumes:
      - ./src:/app/src:ro
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=plataforma_cursos
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  mysql-test:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=testpassword
      - MYSQL_DATABASE=plataforma_cursos_test
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=test_password
    ports:
      - '3307:3306'
    volumes:
      - mysql_test_data:/var/lib/mysql
    restart: unless-stopped
    profiles: ['test']

volumes:
  mysql_data:
  mysql_test_data:
